* Mở đầu

** Giới thiệu
Hiện nay, hầu hết các cơ sở giáo dục đều đã triển khai ứng dụng hệ thống thông tin quản lý, nhằm để tăng hiệu quả trong công việc quản lý chung.
Đó là hệ thống thông tin quản lý đào tạo, quản lý thi, tuy nhiên hệ thống tra cứu văn bằng chứng chỉ phải được công khai theo quy định tại Điều 2 thông tư số 21/2019/TT-BGDĐT.
Bên cạnh đó, những giải pháp tin học hóa nghiệp vụ, số hóa dữ liệu cần đảm bảo nguyên tắc an toàn thông tin của tổ chức và các cá nhân tham gia theo quy định tại Điều 24 luật số 67/2006/QH11.

Môi trường chia sẻ thông tin hiện nay là những mạng truyền thông như mạng internet, trạm thông tin di động, wifi. Những mạng này rất rủi ro cho an toàn thông tin bởi vì những người không được phép có thể dùng cách tấn công nghe lén để xâm phạm thông tin \cite{phạmnguyênkhang2013}. Ngoài thông tin, các thành phần trong mạng cũng là mục tiêu của tấn công mạng \cite{dothanhnghi2018}.

Từ năm 2008, công nghệ chuỗi khối (blockchain technology) được hiện thực hóa với Bitcoin \cite{nakamoto2008bitcoin}, đã đánh dấu sự ra đời cách thức lưu trữ và chuyển giao thông tin hoàn toàn mới.
Một thuộc tính của công nghệ chuỗi khối là sự đồng thuận giữa các thành phần không tin cậy - cùng tham gia vào một hệ thống mạng không tập trung. Công nghệ này đã được rất nhiều nghiên cứu \cite{10.1145/3190508.3190538, ANTWI2021100012, fair2019, 8246573, Fang2020} để hoàn thiện về cơ chế và ứng dụng trong các giải pháp xử lý, truyền tải an toàn thông tin.

Chuỗi khối (blockchain) sử dụng các kỹ thuật mật mã \cite{lequyetthang2016, christofpaar2015, ralphcharlesmerkle1979, shannon-otp} để ghi nhận các giao dịch xảy ra theo thời gian và để kiểm chứng nguồn gốc thông tin.
Theo đó, chuỗi khối như là một cấu trúc dữ liệu (cuốn sổ cái) ghi lại và mã hóa tất cả các giao dịch giữa các thành phần trong hệ thống để bảo đảm tính toàn vẹn thông tin. Công nghệ ngày giúp chống lại sự thoái thác trách nhiệm: một đối tác bất kỳ trong hệ thống không thể từ chối trách nhiệm về hành động mà mình đã thực hiện.
Vì vậy, những đặc tính của công nghệ chuỗi khối rất hữu ích trong việc xử lý và chuyển giao thông tin.

Tuy nhiên, công nghệ chuỗi khối cũng có mặt hạn chế.
Nghiên cứu \cite{CHEN20191122} cho rằng công nghệ này chưa phù hợp để xử lý những giao dịch cần hiệu suất cao hoặc để thay thế cơ sở dữ liệu (database).
Cơ chế lưu trữ của chuỗi khối cũng không dành để lưu dữ liệu lớn.
Do đó cần có giải pháp linh hoạt kết hợp cơ chế lưu trữ ngoài chuỗi khối (off -- chain) bên cạnh khả năng lưu dữ liệu và xử lý hạn chế của công nghệ.

Mục tiêu chính của đề tài là ứng dụng công nghệ Blockchain để lưu trữ thông tin văn bằng, chứng chỉ. Ngoài việc tìm hiểu những khái niệm liên quan công nghệ chuỗi khối với các đặc tính công khai, an toàn, minh bạch, đề tài còn hướng đến nhu cầu dùng công nghệ chuỗi khối để kiểm chứng thông tin văn bằng, chứng chỉ khi thông tin được truy vấn từ cơ sở dữ liệu văn bằng, chứng chỉ bên ngoài chuỗi khối.

** Lý do chọn đề tài

Trung tâm Tin học Trường Đại học An Giang là đơn vị hoạt động về lĩnh vực đào và có chức năng tổ chức thi và cấp chứng chỉ.
Công tác quản lý về đào tạo, tổ chức thi và cấp chứng chỉ tại đơn vị đã được tin học hóa một số nghiệp vụ mang lại hiệu quả đáng kể như ghi danh học viên, quản lý hóa đơn, nhận hồ sơ dự thi, tra cứu điểm thi, và công khai thông tin văn bằng chứng chỉ do đơn vị cấp trên hệ thống website.

Sổ gốc cấp văn bằng, chứng chỉ theo quy định tại Điều 19 thông tư số 21/2019/TT-BGDĐT yêu cầu ghi thông tin cấp phát văn bằng, chứng chỉ cho người được cấp, đã thi đạt sau khi dự thi tại cơ sở tổ chức thi. Sổ gốc cấp văn bằng, chứng chỉ phải được ghi chính xác, đánh số trang, đóng dấu giáp lai, không được tẩy xóa, đảm bảo quản lý chặt chẽ và lưu trữ vĩnh viễn. Tuy nhiên, việc cập nhật thông tin thay đổi vào sổ, theo dõi sổ gốc còn làm thủ công trong những trường hợp như sau:

1. Nhân viên phát văn bằng, chứng chỉ cho người nhận chứng chỉ đến trực tiếp và có giấy tờ khớp thông tin với sổ gốc thì nhân viên phát cho người đó và cập nhật sổ gốc. Ngược lại, nếu giấy tờ người nhận mang theo mà thông tin không khớp với sổ gốc thì nhân viên không phát cho người đó.
   
2. Nhân viên phát văn bằng, chứng chỉ cho người nhận chứng chỉ có giấy ủy quyền đến trực tiếp và có giấy tờ ủy quyền khớp thông tin với sổ gốc thì nhân viên phát cho người đó và cập nhật sổ gốc. Ngược lại, nếu giấy tờ người nhận mang theo mà thông tin không khớp với sổ gốc thì nhân viên không phát cho người đó.
   
3. Văn bằng, chứng chỉ chưa phát phải được quản lý, lưu trữ theo quy định.

Mặt khác những trường hợp 1, 2, dù không phát văn bằng, chứng chỉ vẫn phải so khớp thông tin giấy tờ với sổ gốc, nên công việc chưa được hiệu quả. Thêm vào đó, xử lý hồ sơ giấy có thể gặp một số rủi ro như rách trang giấy, thất lạc,... làm ảnh hưởng đến công tác lưu trữ, bảo quản hồ sơ theo quy định.

** Mục đích nghiên cứu

Đề tài tập trung đề xuất mô hình ứng dụng công nghệ Blockchain trong quản lý văn bằng chứng chỉ nhằm hỗ trợ theo dõi việc cập nhật thông tin cho người sử dụng nhưng vẫn đảm bảo tính minh bạch, công khai và an toàn. Các mục tiêu cụ thể như sau:

1. Phân tích và xây dựng CSDL đáp ứng nghiệp vụ quản lý văn bằng chứng chỉ: cập nhật thông tin sổ gốc cấp văn bằng, chứng chỉ; tra thông tin văn bằng, chứng chỉ.
2. Xây dựng hệ thống website tương tác với người sử dụng, giao diện trực quan và phản hồi nhanh.
3. Xây dựng mạng Hyperledger Fabric và triển khai lưu trữ dữ liệu nhật ký về văn bằng chứng chỉ trên mạng này.

** Đối tượng và phạm vi nghiên cứu

Đối tượng nghiên cứu:

  - Lý thuyết mật mã có liên quan công nghệ chuỗi khối
  - Mô hình mạng thử nghiệm Hyperledger Fabric
  - Ngôn ngữ lập trình PHP, JS, khung phát triển ứng dụng Web
  - Quy định pháp luật về quản lý văn bằng, chứng chỉ

Phạm vi nghiên cứu:

  - Quy trình cấp phát chứng chỉ của Trung tâm Tin học Trường Đại học An Giang
  - Xây dựng hệ thống quản lý văn bằng chứng chỉ ứng dụng công nghệ blockchain.

** Phương pháp nghiên cứu
- Tìm hiểu, phân tích và tổng hợp tài liệu về quản lý văn bằng chứng chỉ (quy định, biểu mẫu hiện hành) và các nền tảng kiến trúc, cơ chế hoạt động của mạng Blockchain.
- Xác định các quy trình nghiệp vụ, yêu cầu của hệ thống, cơ sở dữ liệu, thông tin được lưu trên chuỗi khối.
- Phương pháp thực nghiệm, ghi nhận kết quả và đánh giá kết quả đạt được.
** Ý nghĩa của đề tài

Đề tài có tính ứng dụng cao, bên cạnh việc tìm hiểu kiến thức, những khái niệm liên quan công nghệ chuỗi khối.
Ngoài việc triển khai với bài toán cụ thể tại Trung tâm Tin học Trường Đại học An Giang trong quản lý văn bằng, chứng chỉ, nghiên cứu có thể ứng dụng ở các đơn vị khác có nghiệp vụ tương tự như các trường học, cơ sở đào tạo.

Công nghệ chuỗi khối có khả năng xử lý và chia sẻ thông tin, dữ liệu minh bạch theo thời gian và có độ an toàn cao. Các nghiên cứu về công nghệ chuỗi khối có thể mở rộng ứng dụng trong nhiều lĩnh vực như nông nghiệp, y tế, ngân hàng, vận tải.
** Tiểu kết chương 1
Chương 1 trình bày các mục tiêu của hệ thống cần đạt được trong quá trình nghiên cứu và thực hiện. Chương 2 sẽ tập trung giới thiệu cơ sở lý thuyết quản lý văn bằng chứng chỉ, đặc tính an toàn, bảo mật của công nghệ chuỗi khối, và mô hình mạng thử nghiệm Hyperledger Fabric.
